name: Build

on:
  push:
    branches:
      - main
      - 'releases/**'
    tags:
      - '*'

jobs:
  # build_libreswan:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2
  #     with:
  #       platforms: linux/amd64,linux/arm64,linux/arm64/v8
  #   - name: Set up Docker Buildx
  #     id: buildx
  #     uses: docker/setup-buildx-action@v2
  #     with:
  #       platforms: linux/amd64,linux/arm64,linux/arm64/v8
  #   - name: Inspect builder
  #     run: echo "Platforms - ${{ steps.buildx.outputs.platforms }}"
  #   - name: Login to GitHub Package Registry        
  #     run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  #   - name: Log in to Docker Hub
  #     run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
  #   - name: Build
  #     run: make build -C libreswan REPOSITORY=${{ github.repository }} USER=${{ github.actor }}
  #   - name: Push
  #     run: make push -C libreswan REPOSITORY=${{ github.repository }} USER=${{ github.actor }}
  #   - name: Show images
  #     run: docker images
    
  build_hugo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
    - name: Inspect builder
      run: echo "Platforms - ${{ steps.buildx.outputs.platforms }}"
    - name: Login to GitHub Package Registry        
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - name: Build
      run: make buildx -C hugo REPOSITORY=${{ github.repository }} USER=${{ github.actor }}
    - name: Show images
      run: docker images