name: Build

on:
  push:
    branches:
      - main
      - 'releases/**'
    tags:
      - '*'

jobs:
  build_libreswan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/amd64,linux/arm64
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Inspect builder
      run: echo "Platforms - ${{ steps.buildx.outputs.platforms }}"
    - name: Login to GitHub Package Registry        
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build
      run: make buildx -C libreswan USER=${{ github.actor }}